language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyourideas-nodejs-andrew
  api_key:
    secure: KTYFFMwjFWxKtkyDj8rOdwpFtv3Fvk1/nrZmOz2WuesgvVqNSNFgHocTVnSKaFZ4sTJjQismUr8AXsy2jXjtUXWo7RkBmb6wuuzL97/tlyrsxhz3O4svsV9aMe+iA1THXnPcx7PMjYKEXcKVbCmwHEZ4q3H641mmtPuqB2gZ4sxSQrIlb0MA2HemNXNfjWVL7H3ZqUCyBHwqsVZCCu1sS56UarpPsJSOMq9xLDGwJm+ex7O3jXuOOBZV+M6EhIjtxdp802OWY01nAwC4LBXn4Junvz0+EIjtGDnMgaJP7q42Ggxn/uXIQezSCZGqWGrnPd/3+fvHwJHWGNRhUPzcwWmMKwurGMd4PIANLP8T5FnQ7D5BWMJefIik8304F+m/E+zOgY8zfLy8ropTpwujd3WcZxbQDsghVQbVXFbHAS5/saodST7HE75oobDXQI3R/9ceZwwkX+TIEDADXGES7dq+olfrpkQHQt+Y3UQRSXS5uudshwV5ZTM7nhl6dRM3b8RDuguyZzDhHnBvqHxebQHWL3QVfCr3j8CRmbF+a7B3tWG68mbjab9NYDgzNVBsRKU2YYPXO+MpMdScMFJhQgZNmkx4bgsL2BZsOxps2dMoR+6rQ6dnCno3/+oVuV7zuCZtwu6qgm8775Z9O25/dtDlfzYnM+64nTCODpySkSw=
