language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: cx2A4EJQBD/4J/qridZlFHE5XokDxbjVuZqoZe+ilCJ5JlG3J2TZobLpUx3qE58bssxv0/7+PvxyGwserK7D9vA0O6MLIS1Ojv5P6gSi26RdZhnq2Hku38/qJFIgnDl8ky3QdsMKK8XWd8DGiny7Pkt8YgNpo2OlvJd/JVgAiImVPDOeMSuR4ThcAkuYHbFjj6vTsdFqHqAfD34iOPFhCjK/n7gU79N/H5yu7AfoQPGAFIRRdxKpNjnbmt/M1gpmCBVGcX4XKPDeBykw6FtUzhXiE0IWa+DQ8jozUQXZwndiT5QMJSL3Qn9aEUaSg0tvEgJPadkwFECqUZwZCFzK0sChnNFdsFUyGK2qNQeRa9oFiSeHvK1DfFnvOBiUdVy+0Q9jD+dC4BgaFCi38dnq1mtd3GxTc+qXeKlmWTNFB+6xXraE2iCBAMW5rYoLI7QlyEtXBGZfVVfw9I4YAk86bW/3s6FYzxkYDIBCloQyCutViVxiJjnny7tpPcpGpob8xZe931t0Vi9rbUoPR1UbGt48Lh5/edbEr5YUGfn0QAT6DYElkQ0Mz9FyYtPaohS1tou2GOex7kMa15BITUmrJ54pScf4Ga7VIezOjoyKkJNM3x554Kv06qcNvi0FhwA7/Kv9abnfyeylNjX9fC2bMjYWbOvzXAvJlUEqqGSv0i0=
  app: shareyourideas-nodejs-andrew
  on:
    repo: davidz1113/backend-section
  skip_cleanup: true