language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyourideas-nodejs-andrew
  api_key:
    secure: AdRgQq7Bkg6+FjagEX9y4emAmeTusfvxhCybO8dhWIdYJylRezstZb/+XAi9uWn3C/zB3R9Lp1FZ+4JZashRruGCv2zhGI6+mWcU8SrTjLwkWrB6urZAJ9Xqlk1gcb+UPSJhyDdfJcHiaTRD7D0DuU39AUn93QeAhhrwVc8Tk9UWHE+V9HrI49uIZbl/0Fd439d715wVwwH6rxPpuq4zouzCiPgD3VTCL0Ku+B/8PfmfLo/d1oyqve/uyrt7VkpWQKOGfZFgRrJZZPVjZrQkgIWFFHu8psOpQJ836QLqMfspqV7oUO+9gUSeHaDAzD6KKPQcD3xof2w4kCtMUGllMkANdboJX34fqs5OxqFMN9D9h9D4amk5AKa6nvBlpclXk1lhJkAygJS0csIK47QJNKbucXWtIDil8KYSGJn+VOrVsLbYxSWZgXyPueXWj6GX8CHUhoYTwgiUGEn9z4PBSRubXJtFyu5ggWvJB1aMxKke5qflfjYS+5bTFVR+q8WlsiGUNLC1G9yYiREVhRHxogNE5PlxfULw37+dy55WceXWSSQUzso1ET7M75bEADCR6s7iUoL48g2hPsiGD8jfOOSD1gkuRmO+VPPV4j3EdqjvGJQJgCd9ywstzxhCxDhJ+oJmrFmg8yHF2PF9vf7Y334h69b0eE6/yN/q+8osnfQ=
