language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: WaTj/gcJFsmcJ+qjthxmrhPaJTFTWhLqvaHIAf/xz4aE4ckUViDD1FuJp80oMH6PhVjbDf28l0jiTRbJiiYhz9EYqKiIOHQaj9k1S2n/ysJVcKO4AlsWLgYiWQD0DldUzKgm+2c8BtRM7L3LrfnKpuTzeO9oR6dpeRTlssuQQP+Pg5Vy8lBrFg9FOM5nPoMO16A/SNj2VQMNy+OtuMFot3CHlKX1VQrBPHQJnwG++Vdpd8lTvn9hzTsv3KlWpwcrfoftIfmE8p201n9jX9ML7hSdtx/L9OQO41C7mJ/T8YRv6iyLtAVAC4p7pBstp6VjKmOXGu7OnY88FvL953j4wF+Qj7c0a0osi9G/uUL5hIgYuG1C8ec9YyLgeVIV1Q3wzWDbUlN7qk/6RvcCZ2ymH096dQAg8OvvDLwaBlzojYpk27TlmZJDrxZIpsPO8Fli4rW4c1zEp6tJweenWTmt5iky+cUujvbuqRoMyhWfYJsk0A6kucpxyBcX24rtz2z4mkoYl+CnUeuIZkZAdy+IeAaHiuBoVmB3yrxtEQmR8dmOHQeWmuE7ygGCtqQ3INpTtJxgLHM+/VdMVYDVopFE2zsLoo5DwEG//RqNYDmoLZk2uanFs/x9QU7ZIiSg71o2Vx+yJAga4TOYgQUDWFjUSy0UKhv/5q1zDTy/FL69dXw=
  app: shareyourideas-nodejs-andrew
  on:
    repo: davidz1113/backend-section
