language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: cqfK/jAOyT2m5IN95USwLmMFpHhx4tgTLo90iTxoiBjE0Isp8qF42oxOilPxl9rEf97dvRUKy++FYqpPQaYJq6p6jdPr/af0Fl3G4xVE3FvlV80mmuy7EM1S3bwN/IopMFpLM8CHsIhLhA/SUOe3yFZ08YDfbqQn2Hr3aCGL5qKbZuwsZuAkmT85QJ+gaQ5q4N1hNyYsV/kTEhu63uVVknAyPJIkw+ZIN27ztbjJCZazr1pDGNuznyEhsfia43ukcXKWlVLo7JEGjyCAj7qsqodZ2aB3lGlnHfzMPCLbNMJ7Qq9Bo5+7Sz9LZCjioIa/CIkpqHBo5gnH1QxIa8FdiOGj4httAxd7bagaO5IRfUXMpuH5vLSXIRmHafoX4Qj4bmRotagfRx5ZxDqwUH64NBf08d5MjqZ8IJ+pw0eGzlAFoqroHSJlGO83Txg4AQbTlqVEPxlnTTs4SB9W5RCR4NDsmNAYmjAl/ldKDs6Lm1k0upLZrYruUsRvywBiDnXksJD3FudFxRjvQrXwpZHj6lsMelZcxyWAQJLjo27eLbUnlanEfMw4l2YN1o7DWzciC53bNAkNjpEtEKee2i8xYhVnMc8LmbuC1PeHZ9TKRi0J4/5MzBVji0H9FF7Q0Aplpxnzpw10U42vyKuJ3Mt9NQPRe0cp1c9PGWQ6p4N9+hY=
  app: shareyourideas-nodejs-andrew
  on:
    repo: davidz1113/backend-section
